import type { QrCode } from './types'

export const QR_CODES: QrCode[] = [
  {
    id: '1',
    name: 'Store Static QR',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    type: 'static',
    status: 'active',
    used: null,
    limit: null,
    account: 'Main office · ETB',
    currency: 'ETB',
    amount: null,
    url: 'https://checkout.metrobirr.com/pay/1032/et32x9',
    handle: '@metrobusiness',
  },
  {
    id: '2',
    name: 'Test dynamic qr',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    type: 'dynamic',
    status: 'active',
    used: 1,
    limit: 1,
    account: 'Main office · ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et33x1',
    handle: '@metrobusiness',
  },
  {
    id: '3',
    name: 'Test dynamic qr',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    type: 'dynamic',
    status: 'completed',
    used: 1,
    limit: 1,
    account: 'Main office · ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et34x2',
    handle: '@metrobusiness',
  },
]
