import type { BrandingDetails, PaymentLink } from './types'

export const PAYMENT_LINKS: PaymentLink[] = [
  {
    id: '1',
    name: 'Test multi payment',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    status: 'active',
    used: 1,
    limit: 5,
    account: 'Main office • ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et32x9',
    payers: [
      { id: 'p1', name: 'Abebe Kebede', paidAt: 'Today, 2:46 AM', reference: 'MTCD4532' },
    ],
  },
  {
    id: '2',
    name: 'Test',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    status: 'completed',
    used: 1,
    limit: 1,
    account: 'Main office • ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et33x1',
    payers: [
      { id: 'p2', name: 'Abebe Kebede', paidAt: 'Today, 2:46 AM', reference: 'MTCD4533' },
    ],
  },
  {
    id: '3',
    name: 'Test payment',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    status: 'active',
    used: 1,
    limit: 5,
    account: 'Main office • ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et34x2',
    payers: [],
  },
  {
    id: '4',
    name: 'Test payment',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    status: 'completed',
    used: 1,
    limit: 1,
    account: 'Main office • ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et35x3',
    payers: [
      { id: 'p4', name: 'Abebe Kebede', paidAt: 'Today, 2:46 AM', reference: 'MTCD4534' },
    ],
  },
  {
    id: '5',
    name: 'Test payment',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    status: 'active',
    used: 1,
    limit: 5,
    account: 'Main office • ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et36x4',
    payers: [],
  },
  {
    id: '6',
    name: 'Test payment',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    status: 'completed',
    used: 1,
    limit: 1,
    account: 'Main office • ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et37x5',
    payers: [],
  },
  {
    id: '7',
    name: 'Test payment',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    status: 'active',
    used: 1,
    limit: 5,
    account: 'Main office • ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et38x6',
    payers: [],
  },
  {
    id: '8',
    name: 'Test payment',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    status: 'completed',
    used: 1,
    limit: 1,
    account: 'Main office • ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et39x7',
    payers: [],
  },
  {
    id: '9',
    name: 'Test payment',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    status: 'active',
    used: 1,
    limit: 5,
    account: 'Main office • ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et40x8',
    payers: [],
  },
  {
    id: '10',
    name: 'Test payment',
    createdAt: 'Today, 2:46 AM',
    createdBy: 'Abebe Kebede',
    status: 'completed',
    used: 1,
    limit: 1,
    account: 'Main office • ETB',
    currency: 'ETB',
    amount: 5000,
    url: 'https://checkout.metrobirr.com/pay/1032/et41x9',
    payers: [],
  },
]

export const DEFAULT_BRANDING: BrandingDetails = {
  address: 'Warka tower, Atlas road, Bole, Addis Ababa, Ethiopia',
  website: 'metropshops.com',
  phone: '+251 915001851',
  email: 'testmerhant@metrobirr.com',
  showAddress: false,
  showWebsite: false,
  showPhone: false,
  showEmail: false,
  theme: 'blue',
  merchantName: 'Metro Gateway test account',
}

export const THEME_SWATCHES = [
  { id: 'blue' as const, className: 'bg-[#4B8BF5]' },
  { id: 'purple' as const, className: 'bg-[#8B5CF6]' },
  { id: 'pink' as const, className: 'bg-[#EC4899]' },
  { id: 'teal' as const, className: 'bg-[#14B8A6]' },
]
